services:
  backend:
    build:
      context: ./BACKEND
    ports:
      - "3001:3001"
    env_file:
      - ./BACKEND/.env # Explicitly reference the backend .env file
    volumes:
      - ./BACKEND:/usr/src/app
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build:
      context: ./FRONTEND
    ports:
      - "3000:3000"
    env_file:
      - ./FRONTEND/.env # Explicitly reference the frontend .env file
    volumes:
      - ./FRONTEND:/usr/src/app
    depends_on:
      - backend
    networks:
      - app-network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER} # User for the database
      POSTGRES_PASSWORD: ${DB_PASSWORD} # Password for the database
      POSTGRES_DB: ${DB_NAME} # The actual database name
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
